config/routes.rb
require 'api_constraints'
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, path: 'auth'

  resources :users
  namespace :asset do
    resources :computers
  end
  resources :assets, only: [:index]
  namespace :component do
    resources :cpus, only: [:index, :show, :destroy]
    resources :nics, only: [:index, :show, :destroy]
    resources :ram_modules, only: [:index, :show, :destroy]
  end
  resources :components, only: [:index]
  resources :revisions, only: [:show, :index]
  resources :statuses, only: [:show, :index]
  resources :reports, only: [:show, :index]

  authenticate :user, lambda { |u| u.admin? } do
    get '/sidekiq' => 'dashboards#sidekiq'
    mount Sidekiq::Web => '/sidekiq/monitor'
  end

  namespace :api, defaults: { format: :json } do
    apipie
    scope module: :v1, constraints: ApiConstraints.new( version: 1, default: true ) do
      root 'base#index'
      resources :users, only: [:show]
      resources :assets, only: [:index, :show, :create, :update, :destroy] do
        get 'search', on: :collection
      end
      resources :revisions, only: [:index, :show, :create, :update, :destroy]
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :components, only: [:index, :show, :create, :update, :destroy]
      resources :reports, only: [:index, :show, :create, :update]
    end
  end

  root 'dashboards#index'

end

app/controllers/api/v1/statuses_controller.rb
class Api::V1::StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  def show
  end

  # POST /statuses
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :state)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :state)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>Statuses <small>Overview</small></h1>
</div>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>Name</th>
      <th>Asset</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= visualize_status status.state %></td>
        <td><%= link_to status.name, status %></td>
        <td><%= link_to status.asset.name, status.asset %></td>
        <td><%= status.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/statuses/show.html.erb
<div class="page-header">
  <h1>Statuses <small>Overview</small></h1>
</div>

<div class="panel panel-default show-summary">
  <div class="panel-heading">
    <h2 class="panel-title">Summary</h2>
  </div>
  <div class="panel-body">
    <dl>
      <dt>Name</dt>
      <dd><%= @status.name %></dd>
      
      <dt>Status</dt>
      <dd><%= visualize_status @status.state %></dd>
      
      <dt>Message</dt>
      <dd><%= fill_if_empty @status.message %></dd>
      
      <dt>Asset</dt>
      <dd><%= link_to @status.asset.name, @status.asset %></dd>
      
      <dt>Date</dt>
      <dd><%= l @status.created_at %></dd>
    </dl>
  </div>
</div>

<nav class="contextual">
  <ul class="nav nav-pills">
    <li><%= link_to 'Back', statuses_path %></li>
  </ul>
</nav>