config/routes.rb
require 'api_constraints'
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, path: 'auth'

  resources :users
  namespace :asset do
    resources :computers
  end
  resources :assets, only: [:index]
  namespace :component do
    resources :cpus, only: [:index, :show, :destroy]
    resources :nics, only: [:index, :show, :destroy]
    resources :ram_modules, only: [:index, :show, :destroy]
  end
  resources :components, only: [:index]
  resources :revisions, only: [:show, :index]
  resources :statuses, only: [:show, :index]
  resources :reports, only: [:show, :index]

  authenticate :user, lambda { |u| u.admin? } do
    get '/sidekiq' => 'dashboards#sidekiq'
    mount Sidekiq::Web => '/sidekiq/monitor'
  end

  namespace :api, defaults: { format: :json } do
    apipie
    scope module: :v1, constraints: ApiConstraints.new( version: 1, default: true ) do
      root 'base#index'
      resources :users, only: [:show]
      resources :assets, only: [:index, :show, :create, :update, :destroy] do
        get 'search', on: :collection
      end
      resources :revisions, only: [:index, :show, :create, :update, :destroy]
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :components, only: [:index, :show, :create, :update, :destroy]
      resources :reports, only: [:index, :show, :create, :update]
    end
  end

  root 'dashboards#index'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  # GET /
  def index
  end

  # GET /sidekiq
  def sidekiq
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/index.html.erb
<div class="jumbotron" style="border-radius: 0.5em">
  <div class="container">
    <div class="hidden-xs col-sm-4 col-md-3 col-lg-2">
      <span class="pull-right glyphicon glyphicon-scale" style="font-size: 12em;"></span>
    </div>
    <div class="col-sm-8 col-md-9 col-lg-10">
      <h1>NeinDB</h1>
      <p>Keeping track of your assets</p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Stats 1</h4>
      </div>
      <div class="panel-body">
        <p>Stuff</p>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Stats 2</h4>
      </div>
      <div class="panel-body">
        <p>Stuff</p>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Stats 3</h4>
      </div>
      <div class="panel-body">
        <p>Stuff</p>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/sidekiq.html.erb
<iframe style="width: 100%; height: 950px;" src="<%= sidekiq_web_path %>"></iframe>