config/routes.rb
require 'api_constraints'
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, path: 'auth'

  resources :users
  namespace :asset do
    resources :computers
  end
  resources :assets, only: [:index]
  namespace :component do
    resources :cpus, only: [:index, :show, :destroy]
    resources :nics, only: [:index, :show, :destroy]
    resources :ram_modules, only: [:index, :show, :destroy]
  end
  resources :components, only: [:index]
  resources :revisions, only: [:show, :index]
  resources :statuses, only: [:show, :index]
  resources :reports, only: [:show, :index]

  authenticate :user, lambda { |u| u.admin? } do
    get '/sidekiq' => 'dashboards#sidekiq'
    mount Sidekiq::Web => '/sidekiq/monitor'
  end

  namespace :api, defaults: { format: :json } do
    apipie
    scope module: :v1, constraints: ApiConstraints.new( version: 1, default: true ) do
      root 'base#index'
      resources :users, only: [:show]
      resources :assets, only: [:index, :show, :create, :update, :destroy] do
        get 'search', on: :collection
      end
      resources :revisions, only: [:index, :show, :create, :update, :destroy]
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :components, only: [:index, :show, :create, :update, :destroy]
      resources :reports, only: [:index, :show, :create, :update]
    end
  end

  root 'dashboards#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  STATUS = %w(running success failure)
  WORKER_STATUS = %w(parsing success failure)

  has_many :revisions, as: :trigger
  belongs_to :asset
  belongs_to :user

  validates :status, presence: true, inclusion: STATUS
  validates :parser_status, inclusion: WORKER_STATUS, allow_nil: true
  validates :starttime, presence: true

  def append collector, identifier, text
    return unless text.is_a? String

    @data = {} if @data.nil?
    @data[collector] = {} if @data[collector].nil?
    @data[collector][identifier] = "" if @data[collector][identifier].nil?

    # append the text to the message
    @data[collector][identifier] += "#{text}\n"
  end
end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < Api::V1::BaseController
  before_action :set_report, only: [:show, :edit, :update]

  # GET /reports
  def index
    @reports = Report.all
  end

  # GET /reports/1
  def show
  end

  # POST /reports
  def create
    @report = Report.new(report_params)
    @report.user = current_user

    if @report.save
      # start the right worker
      start_worker

      render :show, status: :created, location: @report
    else
      render json: @report.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /reports/1
  def update
    if @report.update(report_params)
      # start the right worker
      start_worker

      render :show, status: :ok, location: @report
    else
      render json: @report.errors, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:id, :asset_id, :status, :starttime, :endtime).tap do |whitelist|
        whitelist[:data] = params[:report][:data]
      end
    end

    def start_worker
      case @report.status
      when "running"
        # Running reports should have a timeout
        ReportWorker::TimeoutChecker.perform_in(ReportWorker::TimeoutChecker::RUNNING_TIMEOUT, @report.id)
      when "success"
        ReportWorker::Parser.perform_async(@report.id)
      when "failure"
      end
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    # Order the reports decending by the date
    @reports = Report.order("created_at DESC")
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def color_status status
    type = nil

    case status
    when 'success'
      type = 'success'
    when 'failure'
      type = 'danger'
    when 'running'
      type = 'info'
    end

    "<span class=\"label label-#{type}\">#{status.capitalize}</span>".html_safe
  end

  def color_parser_status status
    return '&nbsp'.html_safe if status.blank?

    type = nil

    case status
    when 'success'
      type = 'success'
    when 'failure'
      type = 'danger'
    when 'parsing'
      type = 'info'
    end

    "<span class=\"label label-#{type}\">#{status.capitalize}</span>".html_safe
  end
end

app/views/reports/_data.html.erb
<nav>
  <ol class="breadcrumb">
    <% @report.data.keys.each do |collector| %>
      <li><a href="#<%= collector %>"><%= collector %></a></li>
    <% end %>
  </ol>
</nav>

<% @report.data.each do |collector,information| %>
  <a name="<%= collector %>"></a>
  <h3><%= collector %></h3>
  <div class="row">
  <% information.each do |type,value| %>
    <% unless value.blank? %>
    <div class="col-sm-1">
      <%= type %>
    </div>
    <div class="col-sm-11">
      <pre><%= value %></pre>
    </div>
    <% end %>
  <% end %>
  </div>
<% end %>

app/views/reports/index.html.erb
<div class="page-header">
  <h1>Reports <small>Overview</small></h1>
</div>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Status</th>
      <th>Parser</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= color_status report.status %></td>
        <td><%= color_parser_status report.parser_status %></td>
        <td><%= l report.starttime %></td>
        <% if report.endtime %>
          <td><%= l report.endtime %></td>
        <% else %>
          <td>&nbsp;</td>
        <% end %>
        <td><%= link_to 'Details', report %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/show.html.erb
<div class="page-header">
<h1>Reports <small>Details for a report</small></h1>
</div>

<div class="panel panel-default show-summary">
  <div class="panel-heading">
    <h2 class="panel-title">Summary</h2>
  </div>
  <div class="panel-body">
    <dl>
      <dt>Status</dt>
      <dd><%= color_status @report.status %></dd>

      <dt>Parser</dt>
      <dd><%= color_parser_status @report.parser_status %></dd>

      <dt>Asset</dt>
      <dd><%= link_to @report.asset.name, @report.asset %></dd>
      
      <dt>Started</dt>
      <dd><%= l @report.starttime%></dd>
      
      <dt>Finished</dt>
      <% if @report.endtime %>
        <dd><%= l @report.endtime %></dd>
      <% else %>
        <dd>&nbsp;</dd>
      <% end %>
      
      <dt>Submitted by</dd>
      <% if current_user.admin? %>
        <dd><%= link_to @report.user.name, @report.user %></dd>
      <% else %>
        <dd><%= @report.user.name %></dd>
      <% end %>
    </dl>
  </div>
</div>

<nav class="contextual">
  <ul class="nav nav-pills">
    <li><%= link_to 'Back', reports_path %></li>
  </ul>
</nav>

<h2>Attached data</h2>

<%= render 'data' %>